name: jeremy-chen
favicon: null
layout_spectrum: 0.49332
typography_spectrum: 0.86646
title: "Jeremy Chen's Web Journal"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71808724-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161218'
    - '#999c9a'
    - '#80807e'
    - '#875245'
    - '#acbab1'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
